---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minecraft-secret
  namespace: minecraft
spec:
  encryptedData:
    CF_API_KEY: AgCd/G+THba7ENVWMEUDNtmltDKdVmf702m+4XVfAmGOMbYRiKCXeSZlhObTQl+gEq9TKTVvbz7kCGlMpD/I8l+N7UpTOEEYgTLyk4LQ6Q37HBMxb9p/qi8WoYi/fNlMPWXyg9WFW4WSsxLQ9h01hMhEFEozmTpbrJQa3oCwUftxauF8GZ2gP3kSzLED6b5kFuHDCZUgsVpQ+0gdWK1/ThQmOWrjMime73chjph+PHVY7DxQEHZLdokcSRnFMsepHxa3rmlcfHH1rkGWUqiBEFVUSkKU8CYw0NoxS63PS5TQFMSsu9/bzDKClL93h706OquZHGhESwWzYTlP4rwDVpd8WP1lNaXNySZru086T1u6aGP8q0K0JGQPk1NJfgvbQXJFvesBuUs0wvAs0DciVjAoYwzKjdlNtwIzLEcJiGOcTmA/dKZ/yTn9vdroDMrYzeG5z4wOJQXxllPC75aPvIeZb0jjd9eMILAHrH3Og/siE2FshWS4J0SEyZOo28JmCFW6KW7o7HzDlxk2RweG89fHlaxk0X2OZbb6SbANov9Zql2h1Hi0P4ewYTducQYGvcp2vSLa5oyoXQR49rblsnVcfh/pnPMUo2oqwwN5wiSOmFeYkFlhEdMkAtgDZ9Q6KJAzfmXl3cB89W6KxIS12u2yw8+7/l9QVWUFNaA62c0PKg/0PxMmlMiYlIlaoLcn+G9ouiIkILkO/1VUDAjXv8GJUq2CT/lL7p4NzcCRQPCxOUrTkIxkVd1vNODcNL1E9N7okcYoApQTxNiFRm0=
    rcon-password: AgA7VyzICrk11NkSjyXKzVXDVTwbL9ma4R8ieuWCoXnPRn5GzM21bMicq6qwMMsa8ZW03sTqC5Zs7EPlJq224JLU7zsFws+b6LDqdtlaK2AJPpJsCz1zvuACFJGFe51wZNBxRkKG/Zvavk6OV0rR0hZV3qdVSRApXLLJawfWca26X2MBTXQ9ZsTpBmeJljtuPrHS3GBKhvMpt3fRQ4ZVtLnPNfija2Rz6oUbGsWTzUVo9IDUcNToU30ymYMZYxir4apG1+CO8507fI4kswfY/BMhHM051Ff0ReNBgUg0u+0Vm6/aAn9j6ByzGEY2dnIFYemaxv57qJfXlysCA8Je9OziRCplOQfuj6sOMB10WFQ3h3fQ+8sCW/q4qJBXxzsQ9UcV8XvPECQhFsaIzwwY46aGUkJR4Er9yUjb9ptG3nr6TWUmMw4pGdYeKoZGaRy+ipwOPbm5yGfHOz4zQv9frYk7wSUvmyXu05rdpmY+uIQnx2QkhdjPsZgyNBmxNOR1k88xL+kazMd9EwokR7z4cKeYFvehLwbWpf48voQq6A/6bTs75EK9QfWy9F6/aEYdAqR+5lXj2B001qadUOkGUnrKA88rRCHSw/nx+rHNi2RIN/Bho1xVnrvqQL32nY/+SqDqRElk6XeFDSAp90rECM+sgfSWJ47WjeC4Niv8bk1dSeuLTOQ1RIWbKwdi23W8WIugafdaGTYh24df
  template:
    metadata:
      creationTimestamp: null
      name: minecraft-secret
      namespace: minecraft
