---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minecraft-secret
  namespace: minecraft
spec:
  encryptedData:
    CF_API_KEY: AgClQys05TyJ0Zr2j3lyZGk66jr8KaDvn/+oIc33zqoGStDLNubJX2ZtcgwRgceqJhdKkG0NP8VkNF8jC7uLKGVXsvPX+1oo67FXIpeYCyGNG6hOg4SqEJMTfU4pjbm3Ojwf0dSTWiwPj3ZuXcusf6+XpFhECtqyLenPHyk/PNRuh2SwTvqFdMAY0Z0VXS7u2Duj5CLh2zfVlk04xEU7vpRS8luu//iyoXGUB1GF8aL/USzZ0a0YIq1cYnHh7TiPRj8Hq7NvM2ewzLejcShbcg0xL9TBwPWMsip/9KYjWe/9lJkzc5URgpnrw+yuLlVUzfRqoDSxL/NKekwScxE5RQSG4E7Qs3L3Z7rMFzvjux5SHtCNk/QjSjPv5TBQFCMatn62d8UzocqDtD0aahHXK82cBOdiuktx4VFrzynRarSm0/9JVem6SFyAaHsKaXIHaeWOD8jomk3hWXD89P3fgZNuIQDTKQo1jy08H2LRJXjkHoTlODrroGg6wlxYe6T+tT/mMJ+j+zdoJQGR+4jSPBT9QSjSRa9lhawT57qoPBkLG0aZL8TpXkV6wP3P2fgBrXkWSg9lzn5Wen0+ov0HXBrR+agLqEc5y1uXIem9uaBQWU+0gXq+fQ36EEv3ZUAlxKTNGDU9shiA3M406gfrk7IVE6VSx0aw3sq2mKhKGes7dR21GpkRPasp2s7AF+nehYzAXrDNb+eTHfNlqY+nPLVpChLXDWfA6HSfl2iMMjc=
    rcon-password: AgBRB8TNnQQyDVvAGmCW89Sf/xYgbR7I2Cn4N0os1WQdMYsPYbZYocVnnDYjKGthNjBmctH1iAa/fIGVWN6sZ1IBioFWD5zpYf/uF9Zsc4bQmom0r/Mh+diqFRY94On/W7OkbNH5q1weNnbKOitKd6tljdSQA2ZxcGOg9dVhwNtRnEx7zzdGoVlqxZqa9sOGrJrQZbapa5Z2pUH5CY+NzQy/BCzWAWU78PTszY1Zf0mr0XXGkZ5z0LFARo5Zbk2NvWplJfHr0qhgQCqIwNc+erzHuhP69D6HiCCs6bBHpaRhSHFXq+i1ZO8SX9hMZOG8GJtYZQTN+OrV/qmZQb58oQ1S3vTRU0KFdn8BV2QnsDsHgTuwZahJcisCg6QZPDbQpHoNCiW3tUVW/idOoVzMWMWQU5xUIzNrRnqozaKWhNmme4S+ghb2CBfSZMzwezLpNjjdkTOl6phMn1iGQRjtO8y0uhcJM4XtfAr8GyIISU64GLSEJyBCEZwByDjcgIqeWBbItbE3OVTJypNR69eTKgTbP0GO/P5mXY+UhZ4WaaAw1oJ4JGbE/xkedd5kBJ9OYJQ46Z/rH0T7GDMwOuZwSMOE4z3pqBNMVEZG5FCZeZtvOPbBBPjnM4iyuttr5WnpiDaSg75phxM/pYww3AIg1gLtwyn+nufNRfxVYeiSaqcMmsIPywXVFx3IUX8VKPkvM2RrKHQvNc/8uR4qZqJyieRdvQ==
  template:
    metadata:
      creationTimestamp: null
      name: minecraft-secret
      namespace: minecraft
