---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minecraft-secret
  namespace: minecraft
spec:
  encryptedData:
    CF_API_KEY: AgCJvCPgF90hTYCBAfiQ8Z6s6kKD2gjbSJiAAozbMxC1CZJjy9p/xpYS+mMXj9bh8ftEBK2hPyvLIa+gHZnBjZeqYRK5u2pkGMPUOQQ4vxK3xw/GjvcXzFHNTcQ5qz9naiqncY3haLypMLL2h7QNJZZgWwiWyd6A8gyQBij0nCRg3F1kmfC2FqUIlnZ3v374ALSV3EaFI8TrOOqTuvUm1XCz7SDCKWI/+VpWLvJvY0tFqNvhPISTJmypaIhy+Ek4fWJVPlGCiIBPQs0sXilgV2jibP+Jcfa4K1tuWolb2gQQMB9liXJc45RatrUtRrOcAuANUYeGbJRYaH6kG+rgJ9/XzqyuiG0xEISUUx3uiFfrUOHDOcDfvyakTdJKZwwAbGVk6vDQjvuy0CjaV7v065VufzwH8UkYk9/DleAiJYG0L5A7qVcg0EafJ6B8G+BXoopsKB7NF8ZhtwRnTDo0kGOALg3MiMt2XEGbnWC8UDTa8+5MHvfDi3SkvtjMqlQlltX6VvJyD2wBfxHFh/E9RdPhgmon/HGfSfundaTOaqK0+Xn0z72cHdg47+CFlju0GR/ig8Gk0Tsdwr8fB9PpqSNw29blBMYdG0Ftm3KcQUCpB26YK3E6lnrqpD6zuhWJevAyv2I/4ZURqplnGaLsHCVR/7gC+9fRpKihjhIqdkUIfTCf7Phbz3FWM22jh9Wrvitejy4IOPki6H3cMuW1Wu6ANgpvhgn7t+82KT5YMjfGn/Rhc5FbXrZDdbsW2Epc+pyb76vNHKvA49+kLUU=
    rcon-password: AgAZ/MT5oKpG0tSJ8UtyRNJtztfMU+Kh5q0ticFK735Eo7vdSKF6dXvjwFpKyzDCWIyHxIZ3rB5VR/1iwJKTKJlAMPN06EdaL1OsgzvT/jwyJyEQexBZ+TM5Fel2lJm9HYcW3ftuxtVVrkLo+axX4RjrAwSjRnrJ++gz81ivXtnX3x8P1QHRJ4pMND7FcwTYW0XBnAVWYHzrKh0csUAa+lCK+5/ONruJHxm6QNjMPMoivCG/JLkXY9Su1s9GNMHRc+iDiI+kqU9ahqlcTsjasZqeMPoICvkUNyWleAlupHUdmuzRhY5JAAT5tSDAL1kuYLJA6DMErubPJPCY0TiXJ6Ni4ZqVLGaLUBeNAWNWMclHdUrvqmaorlAjVG3dDsHTDXkU4J+t9lKprG6kL38JHUQbbVCI+9Tyrcl8O7euraRmiba21T88aLHqTJkAFriKbdqEfUqoHh0ixwc/Z4ipFkJu+ozo1IRkh4jQde6yKw7OGSTmNpvvs/QxSmYC8rii7rGVpIrk77VdSMrXxLVWmDnu5cNNpRMZvMDR6Dqz/or2mrLD8ru3dK5GfbGYq5uuKiMYpzFBVCq5iYt6KjfqTLFtJwsv7lHrFUqUzw+IrtRiMvQVQfD0GYAS6v8EuAx4Y0isK7wyKhEkuhhaq019T/obHA707ydDze7CD6tdQtBgWkx7RBNSIijhY2zjShfAvIhjGOjB8wCmTX0c
  template:
    metadata:
      creationTimestamp: null
      name: minecraft-secret
      namespace: minecraft
